version: "3.8"

services:  
    nginx:
      build:
        context: ./nginx
      container_name: nginx
      ports: 
        - "80:80"  
      networks:
        - ismail-net  
      restart : always
      depends_on: 
        - django



    mysql:
      container_name: mysql  
      image: mysql
      ports:
        - "3306:3306"
      networks:
       - ismail-net
      volumes:
        - storage:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db    
      restart: always
      healthcheck:
         test: ["CMD","mysqladmin","ping","-h","localhost", "-uroot","-proot"]
         interval: 10s
         retries: 5  
         timeout: 5s
         start_period: 60s 



    django:
      build:
        context: .
      container_name: django_cont
      env_file:
       - ".env"
      command: sh -c "python manage.py migrate --no-input && gunicorn  notesapp.wsgi --bind 0.0.0.0:8000"   
      ports:
        - "8000:8000"
      networks:
        - ismail-net   
      restart: always
      depends_on:
       - mysql 
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
         interval: 10s
         retries: 5
         timeout: 5s
         start_period: 60s
   


networks:
   ismail-net:

volumes:
  storage:  
  
